### ISSUE TITLE
Wrong icons in status bar

### ISSUE THREAD

**Issue by vanitasvitae** [copperhead/android#34]
It seems like there is some strange issue with status bar icons on the left (notification icons).
Orbot's icon is replaced with the phone with a bell inside and AIMSICD is replaced with a speaker for example.

**Comment by thestinger** [comment]
I can reproduce this, but I expect that it's a CyanogenMod bug. It'll probably be fixed in the next build, we'll see.

**Comment by thestinger** [comment]
Yeah, it was [fixed by this CyanogenMod patch](http://review.cyanogenmod.org/#/c/110126/). It will be included in the next ROM update.

**Comment by thestinger** [comment]
(which is building right now)
