### ISSUE TITLE
Nexus 5 crashes and drains all battery

### ISSUE THREAD

**Issue by vanitasvitae** [copperhead/android#35]
Hi
I lately installed Copperhead on my Nexus 5 and encrypted the OS.
This night my phone must have been crashed or something but the next morning it was dead (I had aeound 75% battery before)

**Comment by vanitasvitae** [comment]
Oops I accidently hit the send button.

I took a look at the battery monitor and there was a big gap from ~2am (75%) untill this morning when I plugged the device into a charger (0%).

How can I see crashlogs or something else from such a crash?

**Comment by thestinger** [comment]
Did you have a lockscreen password set before encrypting?

**Comment by vanitasvitae** [comment]
Yes I did. Then I encrypted, then changed to pin, noticed, that also the encryption password is now a pin and finaly changed the encryption password back to a password.

**Comment by thestinger** [comment]
Crash logs for applications would be in `/data/tombstones` or `/data/anr`. Logcat output isn't persistent by default so I doubt there are any useful logs around.

I'm not really sure why you think it crashed though. I don't have anything to go from here. It's possible that the battery monitoring is very inaccurate (not because of CopperheadOS though).

**Comment by vanitasvitae** [comment]
I cant find any logs for the specific period of time in these directories.
I dont think, the battery monitoring is THAT inaccurate. Will see, if it happens another time, maybe I can deliver more information then.
I cant imagine, that the battery drained from nothing. This morning I recharged my phone to 100% and now it's still at 76%.

**Comment by vanitasvitae** [comment]
One question (I dont want to open a new issue for that): Is tge "bug" where Android shouts out the names of all known wifi networks fixed in cyanogen/copperheadOS? I used to have Wifi Privacy Police installed on my devices and I wonder, if copperhead could implement this feature/include the app by default.

https://f-droid.org/repository/browse/?fdfilter=wifi&fdid=be.uhasselt.privacypolice&fdpage=2

**Comment by thestinger** [comment]
It's something that needs to be done by the OS itself, not an app. It's not possible to use apps for stuff like this because Android will happily kill app-level services at any time.

**Comment by polyzen** [comment]
That would be a great addition. A quick look at the reviews shows there are
issues with wifi login webpages. Worth a separate issue!

**Comment by vanitasvitae** [comment]
My phone froze crashed again this night. When I pushed the power button a few minutes ago, the screen went on and showed the time 0:27 and 98% battery. But then it doesnt respond to any more button clicks or gestures. I restarted it by long pressing the power button and now it works again (53% battery). 

I would really love to gibe you more advanced logs. Is there some kind of app that does more advanced and persistent logging?

**Comment by vanitasvitae** [comment]
I searched Cyanogens Issue tracker and found theese two issues that may be my problem:

https://jira.cyanogenmod.org/browse/CYAN-5867?jql=text%20~%20%22hammerhead%20freeze%22

**Comment by thestinger** [comment]
The useful logs can be obtained with running `adb logcat` if you hook it up to a computer and enable adb in the developer settings. It may not work after the problem occurs though...

**Comment by vanitasvitae** [comment]
The CyanogenMod Issue post suggests trying another kernel. Is that also possible for copperhead or are there vital changes in copperheads kernel?

**Comment by thestinger** [comment]
Using another kernel would mean not having PaX.

**Comment by vanitasvitae** [comment]
Thats a shame. Is nobody else having this problem? My phone is dead every morning. Only exception is when I plugged it to a charger over night, but I dont like that.

**Comment by polyzen** [comment]
I am not. The other night, my battery was ~30 when I went to bed, and 23
when I woke up. More drain than I'd like, but..

**Comment by vanitasvitae** [comment]
I realized, that the crash doesn't appear, when I have an Alarm set on the next morning. That's strange. Maybe it has to do with wake ups of the phone?

**Comment by thestinger** [comment]
Is this still happening on the latest builds?

**Comment by vanitasvitae** [comment]
I had a series of frequent crashes (even with alarm set) on build cm-12.1-20151009-UNOFFICIAL recently.
Currently downloading build cm-12.1-20151013-UNOFFICIAL. Is that the build you mean?

**Comment by thestinger** [comment]
Yeah, that one. I wouldn't expect many changes since 20151013 though. By crashes, what exactly do you mean? Are you interacting with the device when it happens?

Also, do you have gapps installed?

**Comment by vanitasvitae** [comment]
Well I think the device itself is still working...
It happens only when I have my phone laying around. Never happened when I had it in my hand or pocket.
When it crashed and I try to turn the screen on, nothing happens (sometimes it vibrates once when I tap the volume rocker before pushing the power button. So maybe just the UI froze?
Only thing I can do is to reboot the phone by long clicking the power button. Most times I recognize a huge battery drain and when I take a look at the battery monitoring there is just white space for the time the phone was "crashed". 

I installed OpenGApps arm-5.1 pico package.

**Comment by vanitasvitae** [comment]
Updated successful. The crashes mostly happen at night, so maybe I can give you feedback tomorrow. One idea I have: Can the crash occur due to temperature changes? At night I lay my phone on the window ledge with the window half opened (~12-15°Celsius). That's just a thought.

**Comment by thestinger** [comment]
I don't know about that. If this is happening regularly, you could try vanilla CyanogenMod for a while to figure out if it's actually related to CopperheadOS.

**Comment by vanitasvitae** [comment]
Thats a good Idea. Is it possible to dualboot with MultiROM-Managger and disk-encryption turned on? I tried that a few months ago with ubuntu-phone, but it didn't work.

**Comment by thestinger** [comment]
Not sure. If it works with CyanogenMod, it would work with CopperheadOS too.

**Comment by vanitasvitae** [comment]
MutliROM needs a kernel that supports kexec-hardboot. Can I use another kernel temporarily?

**Comment by thestinger** [comment]
Using another kernel would mean not having PaX and MAC randomization. PaX could be the source of whatever error you're encountering, so you'd need to make sure that wasn't it. It wouldn't make much sense to use a setup like that in the long-term since PaX is a big part of CopperheadOS.

**Comment by vanitasvitae** [comment]
Well, I think if the error occurs after the update and I have enough time, I will flash CM to see, whether it is CopperheadOS related or not. I'm hoping for the best though :)

**Comment by polyzen** [comment]
I take it it's a bad idea to enable kexec-hardboot for chos?

**Comment by thestinger** [comment]
I don't intended to deviate from CyanogenMod when it comes to features that aren't related to privacy / security, especially when it comes to adding new features (i.e. new attack surface).

**Comment by thestinger** [comment]
So if you want something like that you should get CyanogenMod to do it.

**Comment by vanitasvitae** [comment]
Bug is not fixed, phone was dead again. Am I the only one with this problem/the only one with an encrypted Nexus 5?

**Comment by thestinger** [comment]
Well, I'm not running into it and I use a Nexus 5 with CopperheadOS as my phone. I haven't heard of anyone else with the issue and there are other people using it too. I'm less sure about the stability on the S4.

**Comment by thestinger** [comment]
I would need logs and other information to be able to approach the problem at all. Right now I don't have anything to go by.

**Comment by thestinger** [comment]
There are some people on #cyanogenmod on freenode with similar issues BTW.

**Comment by Heimdal300** [comment]
I can copy that. I use CM 12.1 on Nexus 5, with device encryption, different passwords and my phone goes off every 5 min if its on battery, although its well charged.

**Comment by rbarlow** [comment]
I have just reported this issue upstream: https://jira.cyanogenmod.org/browse/CYAN-7060

**Comment by thestinger** [comment]
(and I do use encryption on my Nexus 5, and have a matching radio version to the one in that bug report, so those things alone aren't the cause)

**Comment by thestinger** [comment]
So there are actually 2 models of the Nexus 5: D820 (North America) and D821. I'm curious if this only happens on one of them. It has it printed on the back of the phone in a barely legible font right underneath the LG logo.

**Comment by thestinger** [comment]
I have a D820.

**Comment by rbarlow** [comment]
I bought mine in the USA so I assume I have the D820 as well.

**Comment by thestinger** [comment]
Ah, so that's not it either.

**Comment by Heimdal300** [comment]
Just to complete: I have D821.

**Comment by vanitasvitae** [comment]
Im also using a D821.

**Comment by polyzen** [comment]
D820 here. No crashes. Looking forward to Marshmellow and the battery life improvement

**Comment by Heimdal300** [comment]
Must be a problem with the CM-Kernel. Yesterday I flashed ElementalX-N5-4.09-Kernel (http://elementalx.org/devices/nexus-5/) on my phone and this solved the problem. Perhaps a  	temporary solution for people with the same problem on Copperhead.

**Comment by polyzen** [comment]
@Heimdal300:
thestinger commented 2 days ago 
> Using another kernel would mean not having PaX and MAC randomization. PaX could be the source > of whatever error you're encountering, so you'd need to make sure that wasn't it. It wouldn't make > much sense to use a setup like that in the long-term since PaX is a big part of CopperheadOS.

**Comment by polyzen** [comment]
Apparently [we can](http://review.cyanogenmod.org/#/c/74041/) use MultiRom. Thanks to razorloves from #cyanogenmod

**Comment by vanitasvitae** [comment]
Since there were no crashes for me for a very ling time, I would consider this Issue as closed.
