### ISSUE TITLE
Firefox crashes at start-up with a SEGV_ACCERR signal

### ISSUE THREAD

**Issue by thestinger** [copperhead/android#5]
It's not entirely clear what's wrong but it's probably caused by Firefox's custom ELF loader/linker (GeckoLinker). It does crazy things like intentionally causing segmentation faults for lazy library loading and it monkey patches functions in libc.

**Comment by polyzen** [comment]
Just adding a note that this also affects Fennec F-droid

**Comment by thestinger** [comment]
I'm still not sure why this doesn't work, but I suspect that their custom ELF loader/linker is incompatible with a hardening feature that I'm not going to want to remove for the sake of one very screwed up application. Need to narrow down the cause before I can decide what to do though.

**Comment by thestinger** [comment]
Also not really a priority for me because it lacks sandboxing and other hardening features. The default browser will end up being CyanogenMod's new one, which is a fork of Chromium with some added features like built-in ad-blocking.

Would be nice if they provided a way to use the normal linker...

**Comment by thestinger** [comment]
Would be nice if they provided a way to use the normal linker... I expect that it'd work fine.

**Comment by vanitasvitae** [comment]
It seems like Orfox (based on Firefox) also doesnt work.

**Comment by thestinger** [comment]
Yeah, that's expected. I'll spend some time narrowing down the cause of this problem in the next week or two. I have a strong feeling that it's an incompatibility between a hardening feature and their linker though, and I'm not going to want to revert it for their sake. Perhaps they can be convinced to use the regular linker in some cases but I don't think they're going to care... :[

**Comment by thestinger** [comment]
Starting to make some good progress on this. It appears there are two issues here. There's a crash due to a probably intentional memory access error that they intend to catch. I reverted a bunch of features to narrow it down, and I successfully avoided it. There's another *intermittent* start-up error that's not actually a crash, just an abort/exit, but I'll file a new bug for that when the crash is dealt with.

**Comment by thestinger** [comment]
This is fixed and will be included in the next set of releases (likely tonight).

**Comment by thestinger** [comment]
Orfox will still be broken since I only worked around the issue for the Firefox and Firefox Beta app names, so I'll have to deal with that too.

**Comment by vanitasvitae** [comment]
It would be nice if Fennec would be fixed too.

**Comment by thestinger** [comment]
Yeah, that will be fixed too, I just exported the environment variables globally since it's hard to know how many Firefox-based apps there are.

**Comment by polyzen** [comment]
Firefox seems to work fine. Fennec is still crashing.

**Comment by thestinger** [comment]
I know, I haven't released a new ROM with the fix for Fennec and Orfox yet. It is fixed though.

**Comment by thestinger** [comment]
The new ROM is published for the Nexus 5 now.

**Comment by vanitasvitae** [comment]
Works for me for Firefox, Fennec, Orfox. Nice :)

**Comment by polyzen** [comment]
Thank you :)
