### ISSUE TITLE
Is it possible to add support for Galaxy S4 Active SGH-i537?

### ISSUE THREAD

**Issue by tzelch** [copperhead/android#56]
I'm planning to test Copperhead OS for my next Smartphone.
As i'm prone to break phone's i was thinking of getting the S4 Active instead of the S4.
Is the S4 Active easy to port? Or might it even work out of the box?

**Comment by thestinger** [comment]
It seems to be an entirely independent device, so support for it is unrealistic. It would need a port of PaX to the device-specific kernel and other device-specific changes.

**Comment by thestinger** [comment]
The roadmap is to support the Nexus 6, then the Nexus 5x, then the Nexus 6p. It's not possible to give much of a timeline for that though. Support for any more non-Nexus devices is unlikely within the next year or so.
