### ISSUE TITLE
Cellular data not working S4 i9505

### ISSUE THREAD

**Issue by Phobeuscz** [copperhead/android#57]
Greetings, 
I've got issues with cellular data. It works good enough in adb shell, everything ( LAN, DNS, sites ) is pingable, but browser shows me ERR_TIMED_OUT. In built-in terminal emulator, I tried ping localhost without root and I've recieved "socket: permission denied", but under root it worked too without problem.

Wifi worked all the time, so this issue is limited to cellular data

I don't know what else to try.. I also tried wipe cache and dalvik cache, but no success

Some screens:
![screenshot_2015-11-06-15-44-03 1](https://cloud.githubusercontent.com/assets/15690469/10999603/3eec8096-849d-11e5-9275-5b0b7c6763cc.png)

![screenshot_2015-11-06-15-40-56 1](https://cloud.githubusercontent.com/assets/15690469/10999548/01da788e-849d-11e5-8c12-611602455637.png)

**Comment by thestinger** [comment]
Did you enable any of the advanced security features in Settings -> Security? If so, should try disabling them and rebooting.

**Comment by Phobeuscz** [comment]
Nope, all of them in disabled state, at least visually by switches. Didn't hit any of them since flashing ROM ( Last one for now ( 4 Nov 15 ))

**Comment by thestinger** [comment]
So calls and texting work, but not data?

**Comment by Phobeuscz** [comment]
Calls and texting works great, browsing over wifi works well too ( pinging google replies unknown host in terminal, but browsing works ), only cellular data are acting weird like that.

**Comment by thestinger** [comment]
It would be helpful if you could reboot and then provide me with the output from `adb logcat`. It's possible that this is simply a problem with CyanogenMod's APN configuration. Might want to try deleting the APN stuff it autoconfigured and manually entering the information from your provider.

**Comment by thestinger** [comment]
(can give you details on how to do that if you can't figure it out)

**Comment by Phobeuscz** [comment]
I've manage to do that, and also crop info just about cellular connection, APN of my operator is correct. Didn't really saw any issues there. If it'll be needed, I can provide whole log. ( it's after disabling wifi off after fresh boot, I forget it enabled while shutting down )

D/CSLegacyTypeTracker(  651): Sending disconnected broadcast for type 1 NetworkAgentInfo [WIFI () - 101] isDefaultNetwork=true
D/ConnectivityService(  651): sendStickyBroadcast: action=android.net.conn.CONNECTIVITY_CHANGE_IMMEDIATE
D/ConnectivityService(  651): sendStickyBroadcast: action=android.net.conn.CONNECTIVITY_CHANGE
D/ConnectivityService(  651): sendStickyBroadcast: action=android.net.conn.CONNECTIVITY_CHANGE_IMMEDIATE
D/ConnectivityService(  651): sendStickyBroadcast: action=android.net.conn.CONNECTIVITY_CHANGE
I/Email   ( 2011): Unregister all idle mailboxes
D/ConnectivityService(  651): Checking for replacement network to handle request NetworkRequest [ id=1, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]
I/Email   ( 2011): Unregister all idle mailboxes
D/TelephonyProvider( 1204): subIdString = 1 subId = 1
D/Tethering(  651): MasterInitialState.processMessage what=3
D/MediaScannerReceiver(  954): action: android.intent.action.MEDIA_SCANNER_SCAN_FILE path: /storage/emulated/0/media/audio/notifications/facebook_ringtone_pop.m4a
E/SQLiteLog( 1948): (284) automatic index on view_events(_id)
I/UpdateCheckReceiver( 2479): Got connectivity change, has connection: true
I/UpdateCheckReceiver( 2479): Scheduling future, repeating update checks.
D/WeatherUpdateService( 1715): Service started, but shouldn't update ... stopping
I/ActivityManager(  651): Start proc 3054:com.vkontakte.android/u0a63 for broadcast com.vkontakte.android/.NetworkStateReceiver
D/AndroidRuntime( 3054): >>>>>> START com.android.internal.os.RuntimeInit uid 10063 <<<<<<
D/AndroidRuntime( 3054): CheckJNI is OFF
D/AndroidRuntime( 3054): Calling main entry com.android.internal.os.ExecInit
I/SamplingProfilerIntegration( 3054): Profiling disabled.
D/ACRA    ( 3054): ACRA is enabled for com.vkontakte.android, intializing...
D/ACRA    ( 3054): Looking for error files in /data/data/com.vkontakte.android/files
D/ACRA    ( 3054): Looking for error files in /data/data/com.vkontakte.android/files
I/[myTracker]( 3054): Tracker initialized. Version: 1.1.4. ID: 39905392329609327611
I/vk      ( 3054): MT false pref false
I/ActivityManager(  651): Killing 2358:com.android.dialer/u0a7 (adj 15): empty #17
I/wpa_supplicant( 1062): p2p0: CTRL-EVENT-TERMINATING
I/wpa_supplicant( 1062): wlan0: CTRL-EVENT-DISCONNECTED bssid=ee:43:f6:29:c9:5c reason=3 locally_generated=1
I/System  ( 3054): Loaded time zone names for "" in 102ms (98ms in ICU)
D/ConnectivityService(  651): registerNetworkAgent NetworkAgentInfo{ ni{[type: MOBILE[EDGE], state: CONNECTED/CONNECTED, reason: connected, extra: internet.t-mobile.cz, roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false]}  network{null}  lp{{InterfaceName: rmnet_usb0 LinkAddresses: [10.76.92.18/32,]  Routes: [0.0.0.0/0 -> 10.76.92.17 rmnet_usb0,] DnsAddresses: [93.153.117.33,93.153.117.1,] Domains: null MTU: 1500 TcpBufferSizes: 4093,26280,35040,4096,16384,35040}}  nc{[ Transports: CELLULAR Capabilities: SUPL&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN LinkUpBandwidth>=59Kbps LinkDnBandwidth>=236Kbps Specifier: <1>]}  Score{10}  everValidated{false}  lastValidated{false}  created{false}  explicitlySelected{false} }
D/ConnectivityService(  651): NetworkAgentInfo [MOBILE (EDGE) - 102] EVENT_NETWORK_INFO_CHANGED, going from null to CONNECTED
D/ConnectivityService(  651): Adding iface rmnet_usb0 to network 102
D/ConnectivityService(  651): Setting MTU size: rmnet_usb0, 1500
D/ConnectivityService(  651): Adding Route [0.0.0.0/0 -> 10.76.92.17 rmnet_usb0] to network 102
D/ConnectivityService(  651): Setting Dns servers for network 102 to [/93.153.117.33, /93.153.117.1]
D/ConnectivityService(  651): setProvNotificationVisible: E visible=false networkType=0 action=com.android.internal.telephony.PROVISION0
D/NetworkMonitor/NetworkAgentInfo [MOBILE (EDGE) - 102](  651): DefaultState{ when=0 what=532481 target=com.android.internal.util.StateMachine$SmHandler }
D/NetworkMonitor/NetworkAgentInfo [MOBILE (EDGE) - 102](  651): Connected
D/NetworkMonitor/NetworkAgentInfo [MOBILE (EDGE) - 102](  651): EvaluatingState{ when=0 what=532486 arg1=1 target=com.android.internal.util.StateMachine$SmHandler }
D/NetworkMonitor/NetworkAgentInfo [MOBILE (EDGE) - 102](  651): Checking http://connectivitycheck.android.com/generate_204 on internet.t-mobile.cz
D/ConnectivityService(  651): setProvNotificationVisibleIntent: E visible=false networkType=0 extraInfo=null
D/ConnectivityService(  651): notifyType IP_CHANGED for NetworkAgentInfo [MOBILE (EDGE) - 102]
D/ConnectivityService(  651): notifyType PRECHECK for NetworkAgentInfo [MOBILE (EDGE) - 102]
D/ConnectivityService(  651): rematching NetworkAgentInfo [MOBILE (EDGE) - 102]
D/ConnectivityService(  651):    accepting network in place of null
D/ConnectivityService(  651): Switching to new default network: NetworkAgentInfo{ ni{[type: MOBILE[EDGE], state: CONNECTED/CONNECTED, reason: connected, extra: internet.t-mobile.cz, roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false]}  network{102}  lp{{InterfaceName: rmnet_usb0 LinkAddresses: [10.76.92.18/32,]  Routes: [0.0.0.0/0 -> 10.76.92.17 rmnet_usb0,] DnsAddresses: [93.153.117.33,93.153.117.1,] Domains: null MTU: 1500 TcpBufferSizes: 4093,26280,35040,4096,16384,35040}}  nc{[ Transports: CELLULAR Capabilities: SUPL&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN LinkUpBandwidth>=59Kbps LinkDnBandwidth>=236Kbps Specifier: <1>]}  Score{10}  everValidated{false}  lastValidated{false}  created{true}  explicitlySelected{false} }
D/ConnectivityService(  651): Setting tx/rx TCP buffers to 4093,26280,35040,4096,16384,35040
D/ConnectivityManager.CallbackHandler(  919): CM callback handler got msg 524290
D/Tethering(  651): MasterInitialState.processMessage what=3
D/ConnectivityService(  651): notifyType AVAILABLE for NetworkAgentInfo [MOBILE (EDGE) - 102]
D/CSLegacyTypeTracker(  651): Sending connected broadcast for type 0 NetworkAgentInfo [MOBILE (EDGE) - 102] isDefaultNetwork=true
D/ConnectivityService(  651): sendStickyBroadcast: action=android.net.conn.CONNECTIVITY_CHANGE_IMMEDIATE
D/ConnectivityService(  651): sendStickyBroadcast: action=android.net.conn.CONNECTIVITY_CHANGE
D/ConnectivityService(  651): sending Proxy Broadcast for [10.0.0.10] 80
D/ConnectivityManager.CallbackHandler(  919): CM callback handler got msg 524295
D/ConnectivityManager.CallbackHandler(  919): CM callback handler got msg 524295
D/ConnectivityService(  651): notifyType IP_CHANGED for NetworkAgentInfo [MOBILE (EDGE) - 102]
D/ConnectivityService(  651): notifyType IP_CHANGED for NetworkAgentInfo [MOBILE (EDGE) - 102]
I/System  ( 3054): Loaded time zone names for "en_US" in 110ms (103ms in ICU)
I/System  ( 3054): Loaded time zone names for "cs_CZ" in 66ms (60ms in ICU)
D/BluetoothManagerService(  651): Message: 20
D/BluetoothManagerService(  651): Added callback: android.bluetooth.IBluetoothManagerCallback$Stub$Proxy@3573ad5b:true
I/UpdateCheckReceiver( 2479): Got connectivity change, has connection: true
I/UpdateCheckReceiver( 2479): Scheduling future, repeating update checks.

**Comment by Phobeuscz** [comment]
I'm sorry, I'm not able to do any more things with my S4, it stopped reading SIM card ( another issue, probably HW caused, after fixing it up, I'll join back in thread )

**Comment by thestinger** [comment]
Closing this for now. It can be reopened if you or someone else runs into the problem again.
