### ISSUE TITLE
Add pax-exception for info.guardianproject.checkey

### ISSUE THREAD

**Issue by vanitasvitae** [copperhead/android#58]
Hi
Checkey crashes on my device when clicking in the virus total button (the one with the Sigma) when pax-softmode is disabled. When I enable softmode, everything works just fine.

**Comment by thestinger** [comment]
It seems to avoid getting an MPROTECT exception for use of JavaScript in WebView. Strange.

**Comment by thestinger** [comment]
This now has an MPROTECT exception so the problem will be resolved in the next update. However, it seems to indicate that the WebView isn't actually working when JavaScript isn't enabled. Needs more research (#59).
