### ISSUE TITLE
finishing porting all features to CyanogenMod 13.0 (AOSP 6.0)

### ISSUE THREAD

**Issue by thestinger** [copperhead/android#63]

**Comment by polyzen** [comment]
\o/

**Comment by thestinger** [comment]
Still going to be a while before it's ready. CyanogenMod still doesn't have things working properly on the Nexus 9 or Samsung Galaxy S4 yet. I don't really want to use the Nexus 5 for working on this so it's going to be delayed more than I expected.

**Comment by thestinger** [comment]
Switched my Nexus 5 over to Marshmallow-based CopperheadOS so this is now well under way. There's still a lot to do though and a fair number of problems are coming up.

**Comment by polyzen** [comment]
Good to hear :D

**Comment by thestinger** [comment]
Mostly there now. The remaining work is down to the Bionic changes and separate encryption password support. The exec-based spawning model is ported but hits new incompatibilities so that's another problem, but I'd be fine with releasing without that enabled - ideally it can be narrowed down a bit and enabled for normal apps, just not some core ones like Settings.

**Comment by thestinger** [comment]
Closing this bug now and opening up more specific ones. It's pretty close and the initial release is out.
