### ISSUE TITLE
Can't install latest OTA update

### ISSUE THREAD

**Issue by vanitasvitae** [copperhead/android#80]
Hi
I tried installing the latest OTA update on my phone, but the installation failed. Is this update signed with another key? If so, is there a way to install the update over the existing system without losing installed apps/data?

**Comment by polyzen** [comment]
@thestinger made some signing changes, so TWRP won't let you do your thing. If you would like to update without wiping, you will need to use their current (as of yesterday) recovery image. Their web dev went AWOL, so it is not yet on the download page.

    thestinger | https://paste.xinu.at/dEne/
    thestinger | apply update
    thestinger | sideload
    thestinger | I upgraded from cm-12.1 to cm-13.0 copperhead without a wipe

If you're coming from 12.1 and have gapps installed, you may want to read [this](http://opengapps.org/#downloadsection). The opengapps pico package works here.

**Comment by thestinger** [comment]
I'll leave this open for now so other people can see it. Uploading the recovery images is a priority but it's  difficult right now.

**Comment by thestinger** [comment]
The latest release is accompanied by a recovery image, and it will let you update: https://copperhead.co/android/downloads?device=hammerhead.

**Comment by thestinger** [comment]
Note that if you have gapps, it's a lot more complicated (just as it is with CyanogenMod). You need to wipe /system, install the new OS and then install the new version of gapps. So upgrading will be a bit complicated since you need to wipe /system with TWRP, switch to Copperhead's recovery to sideload the OS, and then switch back to TWRP to sideload the new gapps version because our recovery requires that everything is signed with our key. There's still no need to wipe your user data, but I highly recommend backing it up first for obvious reasons :P.

**Comment by vanitasvitae** [comment]
Reinstalled the latest Version after backing up my apps and data.

Nice work bzw :)

**Comment by vanitasvitae** [comment]
The problem is still there for me. To switch from 12 to 13, I wiped everything (I set any flag in TWRP) and sideloaded the new rom. For some reason my old encryption password was still set, which I didnt expected but its OK :) Now I wanted to update to the latest Version (20151213) but I still get the error that TWRP cant install due to incompatible data. What do you suggest? Should I switch to Copperhead Recovery?

**Comment by thestinger** [comment]
If the old encryption password was set, data wasn't formatted. Formatting data would fix the problem. Copperhead Recovery also wouldn't have the problem because it just validates the key, it doesn't do this check.

**Comment by vanitasvitae** [comment]
Ah thats unfortunate. I was so convinced that I formatted data... Is it a big deal to switch to Copperhead Recovery? Would it delete my fikes and apps?

**Comment by thestinger** [comment]
No, it won't delete anything. I don't think over-the-air updates work with it yet though so you'll need to sideload them for now. That will be fixed soon.

**Comment by vanitasvitae** [comment]
Was there again a bigger change to signing? Copperhead Recovery don't want me to update by sideloading.

**Comment by thestinger** [comment]
The CyanogenMod-based operating system was dropped. It's now a new AOSP-based operating system with new signing keys. There's no upgrade path from one to the other, it requires a full wipe.

**Comment by vanitasvitae** [comment]
Ah okay. Thank you.
