### ISSUE TITLE
Galaxy S4 autorotate screen not works

### ISSUE THREAD

**Issue by lightman0** [copperhead/android#84]
Hello!

On my Galaxy S4 (jfltexx) screen autorotation not works: always portrait orientation of the screen.

Thanks.

**Comment by thestinger** [comment]
Are you on the latest release (cm-12.1-20151209)? This works here. You might want to try toggling the portrait mode orientation lock on and off.

**Comment by thestinger** [comment]
Closing as this appears to work correctly. Going to need confirmation that it occurs on the latest release with the orientation lock disabled before looking into it.
