### ISSUE TITLE
Galaxy S4 OGT cable plugin with flash causes reboot the device

### ISSUE THREAD

**Issue by lightman0** [copperhead/android#85]
Hello!

On my Galaxy S4 (jfltexx) always ocurrs device reboot after plugin OTG flash memory.

Thanks.

**Comment by thestinger** [comment]
I expect that this is an issue inherited from CyanogenMod. I've come to the conclusion that CyanogenMod is too unstable to be used as the basis for CopperheadOS, so I'm moving the project to being based directly on AOSP. Sadly, that means support for the S4 has to be dropped. It was a lot of work to get it to the level that it is today (PaX, etc.) but it's unrealistic to keep supporting it.
