### ISSUE TITLE
Reboot after N password / PIN attempts?

### ISSUE THREAD

**Issue by bitterman1970** [copperhead/android#86]
Will future builds include the ability to reboot the device after N lock screen password / PIN attempts?

**Comment by thestinger** [comment]
Yes, it's planned: https://github.com/copperhead/android/issues/11. Note that the OS is currently undergoing a major transition to being based on AOSP instead of CyanogenMod. Not currently working on implementing new features, even small ones like this.

**Comment by thestinger** [comment]
This is now implemented.
